services:

  backend:
    build: ./backend
    container_name: task_manager_backend
    ports:
      - "5000:5000"
    volumes:
      - sqlite_data:/app/data
    environment:
      - PORT=5000
      - DATABASE_URL=/app/data/task
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: task_manager_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  sqlite_data:

networks:
  app-network:
    driver: bridge
